/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-tertiary": "#003825",
              "secondary-fixed-dim": "#68dba9",
              "tertiary-fixed": "#68fcbf",
              "on-primary-container": "#007128",
              "on-primary-fixed": "#002107",
              "on-tertiary-container": "#006f4d",
              "text-secondary": "#A1A1AA",
              "on-secondary-fixed": "#002114",
              "on-background": "#e2e2e8",
              "surface-container-low": "#1a1c20",
              "tertiary-fixed-dim": "#45dfa4",
              "text-primary": "#FFFFFF",
              "secondary": "#68dba9",
              "primary-fixed": "#6bff83",
              "surface-container": "#1e2024",
              "glass-border": "rgba(255, 255, 255, 0.1)",
              "surface-charcoal": "#1A1D23",
              "background": "#111317",
              "surface": "#111317",
              "on-error": "#690005",
              "on-secondary-container": "#00311f",
              "outline": "#849581",
              "inverse-primary": "#006e27",
              "on-secondary-fixed-variant": "#005137",
              "surface-variant": "#333539",
              "surface-container-lowest": "#0c0e12",
              "surface-container-high": "#282a2e",
              "error-container": "#93000a",
              "on-surface": "#e2e2e8",
              "secondary-container": "#25a475",
              "secondary-fixed": "#85f8c4",
              "on-tertiary-fixed": "#002114",
              "surface-dim": "#111317",
              "surface-tint": "#00e55b",
              "outline-variant": "#3b4b3a",
              "primary-container": "#00ff66",
              "primary-fixed-dim": "#00e55b",
              "surface-bright": "#37393e",
              "tertiary-container": "#62f7ba",
              "tertiary": "#ebfff2",
              "on-surface-variant": "#b9ccb5",
              "on-tertiary-fixed-variant": "#005137",
              "on-secondary": "#003825",
              "surface-container-highest": "#333539",
              "error": "#ffb4ab",
              "primary": "#edffe8",
              "inverse-surface": "#e2e2e8",
              "on-primary-fixed-variant": "#00531b",
              "on-error-container": "#ffdad6",
              "inverse-on-surface": "#2f3035",
              "warning-amber": "#FBBF24",
              "on-primary": "#003911"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "section-gap": "120px",
              "stack-lg": "32px",
              "stack-sm": "8px",
              "gutter": "24px",
              "stack-md": "16px",
              "container-max": "1280px",
              "margin-mobile": "20px"
      },
      "fontFamily": {
              "headline-xl": ["Outfit"],
              "display-lg": ["Outfit"],
              "label-sm": ["Inter"],
              "headline-xl-mobile": ["Outfit"],
              "body-md": ["Inter"],
              "headline-md": ["Outfit"],
              "body-lg": ["Inter"],
              "display-lg-mobile": ["Outfit"]
      },
      "fontSize": {
              "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "display-lg": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-xl-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
}
